# Rustfmt configuration for the entire workspace
# See: https://rust-lang.github.io/rustfmt/

# Edition
edition = "2021"

# Line width
max_width = 100

# Indentation
hard_tabs = false
tab_spaces = 4

# Line endings
newline_style = "Unix"

# Comments
wrap_comments = true
format_code_in_doc_comments = true
format_strings = true

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Expressions
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true

# Other formatting
remove_nested_parens = true
normalize_comments = true
normalize_doc_attributes = true
format_doc_comment_code_blocks = true

# Chain formatting
chain_width = 80
single_line_if_else_max_width = 50

# Function formatting
fn_args_layout = "Tall"
fn_params_layout = "Tall"
fn_single_line = false

# Control flow
control_brace_style = "AlwaysSameLineWhere"
where_single_line = false

# Structs and enums
struct_lit_single_line = true
struct_lit_width = 18
struct_variant_width = 18
enum_discrim_align_threshold = 0

# Doc comments
doc_comment_code_block_width = 100

# Heuristics
use_small_heuristics = "Default"
