[package]
name = "treecrdt-wasm"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "WASM bridge for TreeCRDT."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
treecrdt-core = { path = "../treecrdt-core", features = ["serde"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
